In [2]:
import pandas as pd
import numpy as np
import polars as pl
import scipy
from scipy import stats
from scipy.stats import binom, poisson, norm, t
import seaborn as sns
import matplotlib
import matplotlib.pyplot as plt
import pylab
from pylab import legend
from pylab import plot,show,title,xlabel,ylabel

In [ ]:
df = pl.read_excel("")

# Paired Test

In [3]:
before = np.array([12,14,10,9,8,13])
after = np.array([11.8,9.7,11.3,8.2,7.2,12.3])

- Ho | before - after  | : (excpected to be high, Positive Difference)
- Ha | after  - before | : (Output will be negative)

In [4]:
d = (before - after)

In [5]:
d

array([ 0.2,  4.3, -1.3,  0.8,  0.8,  0.7])

In [6]:
np.mean(d)

np.float64(0.9166666666666665)

In [46]:
import statsmodels
from statsmodels import stats
import statsmodels.api as sm
from statsmodels.stats import weightstats as ssw
from statsmodels.formula.api import ols

# Import the required function from statsmodels library
from statsmodels.stats.multicomp import pairwise_tukeyhsd

# Now you can use the function (note: correct function name is pairwise_tukeyhsd, not pairwise_tukeysd)
print(pairwise_tukeyhsd(df.Col2, df.Col1))

Multiple Comparison of Means - Tukey HSD, FWER=0.05
====================================================
group1 group2 meandiff p-adj   lower   upper  reject
----------------------------------------------------
     A      B  10.3968 0.0107  2.2907 18.5029   True
     A      C   4.4107 0.3919 -3.9141 12.7355  False
     B      C  -5.9861 0.1549 -13.802  1.8298  False
----------------------------------------------------

In [11]:
ssw.ttost_paired(before,after, low=2,upp=2)

(np.float64(0.8954696830206994),
 (np.float64(-1.4413160909218492),
  np.float64(0.8954696830206994),
  np.float64(5.0)),
 (np.float64(-1.4413160909218492),
  np.float64(0.10453031697930062),
  np.float64(5.0)))

In [12]:
scipy.stats.ttest_1samp(before-after,popmean=2,alternative='less')

TtestResult(statistic=np.float64(-1.4413160909218492), pvalue=np.float64(0.10453031697930062), df=np.int64(5))

In [15]:
# BTS calculation of above commmands/Equation
(np.mean(d)-2)/((np.std(d,ddof=1))/6**0.5)

np.float64(-1.4413160909218492)

In [17]:
t.cdf(-1.4413160909218492,5)

np.float64(0.10453031697930062)

- 4th Step
  
======================================================================================
# ANOVA test 
======================================================================================
- (ANalysis of VAraince)
   -

In [29]:
dfA = pd.DataFrame({'Col1':np.repeat('A',7),'Col2':np.random.randint(10,30,7)})
dfB = pd.DataFrame({'Col1':np.repeat('B',9),'Col2':np.random.randint(20,40,9)})
dfC = pd.DataFrame({'Col1':np.repeat('C',8),'Col2':np.random.randint(15,30,8)})
df = pd.concat([dfA,dfB,dfC])

In [30]:
df

  Col1  Col2
0    A    19
1    A    10
2    A    27
3    A    21
4    A    26
5    A    10
6    A    11
0    B    39
1    B    27
2    B    36
3    B    22
4    B    21
5    B    37
6    B    25
7    B    22
8    B    24
0    C    29
1    C    18
2    C    22
3    C    18
4    C    19
5    C    21
6    C    24
7    C    26

In [38]:
# Import the necessary function from statsmodels
# ordinary list square
from statsmodels.formula.api import ols

# Now you can use the ols function
mod1 = ols('Col2 ~ Col1', df).fit()

In [39]:
tb1 = sm.stats.anova_lm(mod1)

In [41]:
tb1

            df      sum_sq     mean_sq        F    PR(>F)
Col1       2.0  436.640873  218.320437  5.36105  0.013152
Residual  21.0  855.192460   40.723450      NaN       NaN

In [47]:
# Import the required function from statsmodels library
from statsmodels.stats.multicomp import pairwise_tukeyhsd

# Now you can use the function (note: correct function name is pairwise_tukeyhsd, not pairwise_tukeysd)
print(pairwise_tukeyhsd(df.Col2, df.Col1))

Multiple Comparison of Means - Tukey HSD, FWER=0.05
====================================================
group1 group2 meandiff p-adj   lower   upper  reject
----------------------------------------------------
     A      B  10.3968 0.0107  2.2907 18.5029   True
     A      C   4.4107 0.3919 -3.9141 12.7355  False
     B      C  -5.9861 0.1549 -13.802  1.8298  False
----------------------------------------------------