# Exploratory Data Analysis

In [122]:
# Step 1: Data Cleaning
# Step 2: Data Validation (Checking for data inconsistency in the dataset)

In [ ]:
# Step 1 : df.info()

In [123]:
import numpy as np
import pandas as pd

In [124]:
df = pd.read_excel("data1.xlsx")
df.head()

  Category
0        C
1        D
2        C
3        A
4        B

In [125]:
df.isnull().sum()

Category    80
dtype: int64

In [126]:
df.iloc[np.where(df.isnull())[0]]

    Category
9        NaN
11       NaN
15       NaN
32       NaN
35       NaN
..       ...
476      NaN
477      NaN
490      NaN
492      NaN
494      NaN

[80 rows x 1 columns]

In [127]:
80/df.shape[0]

0.16

In [128]:
from collections import Counter
Counter(df.Category).most_common()

[('B', 113), ('A', 112), ('C', 101), ('D', 94), (nan, 80)]

In [129]:
df2 = df.Category.fillna('B')

In [130]:
df2.isnull().sum()

np.int64(0)

In [131]:
df.Category.value_counts()

Category
B    113
A    112
C    101
D     94
Name: count, dtype: int64

In [132]:
props = pd.DataFrame(df.Category.value_counts())
props.head()

          count
Category
B           113
A           112
C           101
D            94

In [133]:
props['proportion'] = props['count']/sum(props['count'])

In [134]:
props.head()

          count  proportion
Category
B           113    0.269048
A           112    0.266667
C           101    0.240476
D            94    0.223810

In [135]:
random_values = np.random.choice(['A','B','C','D'], size=80, p=props.proportion)
random_values

array(['D', 'B', 'D', 'C', 'B', 'D', 'D', 'B', 'B', 'A', 'A', 'B', 'C',
       'A', 'D', 'C', 'A', 'A', 'A', 'B', 'C', 'B', 'A', 'D', 'D', 'A',
       'A', 'A', 'A', 'B', 'D', 'A', 'B', 'C', 'A', 'D', 'B', 'A', 'B',
       'A', 'D', 'D', 'B', 'C', 'A', 'C', 'C', 'B', 'B', 'D', 'D', 'D',
       'A', 'D', 'D', 'A', 'B', 'A', 'C', 'C', 'D', 'B', 'B', 'A', 'A',
       'D', 'D', 'C', 'B', 'B', 'D', 'A', 'C', 'A', 'D', 'C', 'C', 'A',
       'B', 'B'], dtype='<U1')

In [136]:
ind = np.where(df.Category.isnull())
ind[0]

array([  9,  11,  15,  32,  35,  38,  47,  48,  58,  59,  62,  64,  80,
        81,  82,  84,  95,  98, 122, 123, 140, 156, 161, 163, 164, 165,
       166, 167, 170, 174, 176, 177, 188, 192, 193, 212, 217, 223, 227,
       231, 237, 238, 246, 248, 250, 254, 257, 260, 267, 268, 269, 278,
       281, 287, 303, 328, 329, 333, 342, 345, 349, 357, 382, 384, 387,
       404, 406, 441, 445, 447, 451, 456, 459, 464, 471, 476, 477, 490,
       492, 494])

In [137]:
df.loc[ind[0],'Category'] = random_values

In [138]:
df.isnull().sum()

Category    0
dtype: int64

In [140]:
df1 = pd.read_excel("data2.xlsx")
df1

    Category  Continuous_Value
0          C      -4008.098297
1          D      -3887.888132
2        NaN      -3712.188312
3          C      -3416.823821
4          D      -5845.073897
..       ...               ...
995        C       4254.526508
996        D       4056.149295
997        A               NaN
998        A       4734.230414
999        B               NaN

[1000 rows x 2 columns]

In [143]:
df1.isnull().sum()

Category            150
Continuous_Value    120
dtype: int64

In [148]:
df1.Continuous_Value = df1.Continuous_Value.fillna(df1.Continuous_Value.median())

In [151]:
df1.describe()

       Continuous_Value
count       1000.000000
mean        4991.109176
std         2203.245879
min        -7872.761200
25%         4412.886056
50%         5030.236615
75%         5564.477507
max        19916.251763

In [152]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 2 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Category          850 non-null    object
 1   Continuous_Value  1000 non-null   float64
dtypes: float64(1), object(1)
memory usage: 15.8+ KB

In [153]:
import matplotlib.pyplot as plt

In [203]:
x1 = [12, 14, 15, 15, 16, 18, 19, 20, 21, 22, 22, 23, 25, 25, 26, 28, 29, 30, 31, 32, 35, 38, 42, 65, 82]

In [204]:
x1 = pd.DataFrame(x1)

In [197]:
pd.options.plotting.backend = "plotly"
fig = x1.plot(kind = "box")
fig.show()

In [209]:
q1 = np.percentile(x1,25)
q2 = np.percentile(x1,50)
q3 = np.percentile(x1,75)
IQR = q3-q1
lower_fence = q1-(1.5*IQR)
if lower_fence<0:
    lower_fence=0
upper_fence = q3+(1.5*IQR)
min_value = min(x1)
max_value = max(x1)
# highest_value_betwn_q3uf = max(x for x in x1 if q3 <= x <= upper_fence)
# lowest_value_betwn_q1up = min(x for x in x1 if q1 >= x >= lower_fence)
print(highest_value_betwn_q3uf)
print(lowest_value_betwn_q1up)
print(f"Lower Quartile (q1): {q1}")
print(f"Upper Quartile (q3): {q3}")
print(f"Median: (q2): {q2}")
print(f"Lower Fence: {lower_fence}")
print(f"Upper Fence: {upper_fence}")

42
12
Lower Quartile (q1): 19.0
Upper Quartile (q3): 31.0
Median: (q2): 25.0
Lower Fence: 1.0
Upper Fence: 49.0

In [159]:
np.percentile(x1,25)

np.float64(19.0)

In [160]:
np.percentile(x1,50)

np.float64(25.0)

In [162]:
np.percentile(x1,75)

np.float64(31.0)

In [163]:
max(x1)

82

In [ ]:
df